model:
  type: "NN MLP"
  param_format: "optuna"

nn:
  hidden_layer_sizes: [50, 100, "[50,25]", "[100,50]"] # Att: adiciona [100,50]
  activation: ['relu']
  alpha: [0.1, 1]
  batch_size: [128, 256, 512]
  max_iter: [1000, 2000] # Att: remove 500 e adiciona 2000
  early_stopping: [true]

train:
  test_size: 0.2
  cv: 4
  random_state: 42

cross_val:
  n_jobs: 2
  scoring: "recall"
  refit: "recall"
  verbose: 1
  n_trials: 15 # Att: aumenta de 10 para 15

file: "nn_mlp_6"
