model:
  type: "NN MLP"
  param_format: "optuna"

# Att: simplifica hidden_layer_sizes, alpha; reduz n_trials

nn:
  hidden_layer_sizes: [50, 100, "[50,25]"]
  activation: ['relu']
  alpha: [0.1, 1]
  batch_size: [128, 256, 512]
  max_iter: [500, 1000]
  early_stopping: [true]

train:
  test_size: 0.2
  cv: 4
  random_state: 42

cross_val:
  n_jobs: 2
  scoring: "recall"
  refit: "recall"
  verbose: 1
  n_trials: 5

file: "nn_mlp_4"
