model:
  type: 'XGBoost'
  param_format: 'grid'
  params:
    n_estimators: [100, 200]
    max_depth: [3, 4, 5]
    learning_rate: [0.01, 0.1]
    subsample: [0.7, 0.9, 1.0]
    colsample_bytree: [0.7, 0.9, 1.0]
    gamma: [0, 0.1, 0.2]

train:
  test_size: 0.2
  cv: 3
  random_state: 42

file: 'xgb_grid_1'