model:
  type: 'XGBoost'
  param_format: 'grid'
  params:
    #Att: reduzindo opções de parâmetros para usar dataset maior
    n_estimators: [100, 150]
    max_depth: [4, 5]
    learning_rate: [0.01, 0.05]
    subsample: [0.6, 0.8, 1.0]
    colsample_bytree: [0.6, 0.8, 1.0]
    gamma: [0, 0.01]
    min_child_weight: [1, 3, 5]
    scale_pos_weight: [20, 50, 100]
  fixed_params:
    objective: 'binary:logistic'
    tree_method: 'hist'

train:
  test_size: 0.2
  cv: 3
  random_state: 42

cross_val:
  n_jobs: 2
  scoring: 'recall'
  refit: 'recall'
  verbose: 1
  n_trials: 10

file: 'xgb_7'